In [42]:
#Importing important libraries
import numpy as np
from scipy.linalg import fractional_matrix_power
float_formatter = lambda x: "%.3f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})


In [46]:
A = np.array([[0.0 , 0.8 , 0.6 , 0.0 , 0.1 , 0.0 ],[ 0.8 , 0.0 , 0.8 , 0.0 , 0.0 , 0.0 ],[ 0.6 , 0.8 , 0.0 , 0.2 , 0.0 , 0.0 ],[ 0.0 , 0.0 , 0.2 , 0.0 , 0.8 , 0.7 ],[ 0.1 , 0.0 , 0.0 , 0.8 , 0.0 , 0.8 ],[ 0.0 , 0.0 , 0.0 , 0.7 , 0.8 , 0.0 ]])
print('Adjacency matrix:')
print(A)

Adjacency matrix:
[[0.000 0.800 0.600 0.000 0.100 0.000]
 [0.800 0.000 0.800 0.000 0.000 0.000]
 [0.600 0.800 0.000 0.200 0.000 0.000]
 [0.000 0.000 0.200 0.000 0.800 0.700]
 [0.100 0.000 0.000 0.800 0.000 0.800]
 [0.000 0.000 0.000 0.700 0.800 0.000]]


In [47]:
# degree matrix
D = np.diag(np.sum(np.array(A), axis=1))
print('Degree matrix:')
print(D)
# laplacian matrix
LU = D - A
print('Unnormalized Laplacian matrix:')
print(LU)
LN = np.matmul(fractional_matrix_power(D,-0.5),LU,fractional_matrix_power(D,-0.5))
print('Normalized Laplacian matrix:')
print(LN)

Degree matrix:
[[1.500 0.000 0.000 0.000 0.000 0.000]
 [0.000 1.600 0.000 0.000 0.000 0.000]
 [0.000 0.000 1.600 0.000 0.000 0.000]
 [0.000 0.000 0.000 1.700 0.000 0.000]
 [0.000 0.000 0.000 0.000 1.700 0.000]
 [0.000 0.000 0.000 0.000 0.000 1.500]]
Unnormalized Laplacian matrix:
[[1.500 -0.800 -0.600 0.000 -0.100 0.000]
 [-0.800 1.600 -0.800 0.000 0.000 0.000]
 [-0.600 -0.800 1.600 -0.200 0.000 0.000]
 [0.000 0.000 -0.200 1.700 -0.800 -0.700]
 [-0.100 0.000 0.000 -0.800 1.700 -0.800]
 [0.000 0.000 0.000 -0.700 -0.800 1.500]]
Normalized Laplacian matrix:
[[1.225 -0.653 -0.490 0.000 -0.082 0.000]
 [-0.632 1.265 -0.632 0.000 0.000 0.000]
 [-0.474 -0.632 1.265 -0.158 0.000 0.000]
 [0.000 0.000 -0.153 1.304 -0.614 -0.537]
 [-0.077 0.000 0.000 -0.614 1.304 -0.614]
 [0.000 0.000 0.000 -0.572 -0.653 1.225]]


In [54]:
e, v = np.linalg.eig(LU)
# eigenvalues
print('eigenvalues:')
print(e)
# eigenvectors
print('eigenvectors:')
print(np.around(v,decimals=3))

eigenvalues:
[0.000 0.188 2.084 2.285 2.469 2.573]
eigenvectors:
[[-0.408 -0.408 0.647 0.305 -0.379 -0.106]
 [-0.408 -0.442 -0.014 -0.305 0.706 -0.215]
 [-0.408 -0.371 -0.638 -0.045 -0.388 0.368]
 [-0.408 0.371 -0.339 0.455 -0.001 -0.612]
 [-0.408 0.405 0.166 0.305 0.351 0.652]
 [-0.408 0.445 0.178 -0.716 -0.289 -0.087]]
